name: Deploy production

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        id: smart-vercel
        with:
          node_version: "14"
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
